export const projects = [
  {
    id: 'agrichain',
    name: 'AgriChain',
    logo: '/logos/agrichain.png',
    featured: true,
    tagline: 'Blockchain Parametric Crop Insurance',
    desc: 'A decentralized application where farmers receive automatic insurance payouts when rainfall drops below a threshold, no manual claims, no middlemen. Powered by a cryptographically signed offchain weather oracle.',
    tags: ['Solidity', 'Hardhat', 'Ethers.js', 'React', 'Node.js', 'MongoDB', 'Firebase'],
    liveUrl: 'https://agrichain.tech/',
    githubUrl: 'https://github.com/sejeeswarank/AgriChain',
    metrics: [],
    status: 'ongoing',
    pipeline: [
      { icon: 'user', label: 'Farmer Buys Policy', sub: 'React + MetaMask' },
      { icon: 'cloud', label: 'Oracle Fetches Weather', sub: 'Open Meteo API + Signed' },
      { icon: 'link', label: 'Smart Contract Verifies', sub: 'Solidity on Ethereum' },
      { icon: 'check', label: 'Automatic Payout', sub: 'No manual claim needed' },
    ],
  },
  {
    id: 'kctracker',
    name: 'KCTracker',
    logo: '/logos/kctracker.png',
    featured: false,
    tagline: 'Bank Statement Ledger System',
    desc: 'Auto-detects 25+ Indian banks that converts raw PDF, CSV, Excel transaction data into structured financial ledgers, 10 phase normalization pipeline, Fernet encryption for passwords, Google Drive sync.',
    tags: ['Python', 'Flask', 'SQLite', 'pandas', 'pdfplumber', 'Fernet', 'Chart.js'],
    liveUrl: null,
    githubUrl: 'https://github.com/sejeeswarank/KCTracker',
  },
  {
    id: 'blocklens', logoBg: '#111111',
    name: 'BlockLens',
    logo: '/logos/blocklens.png',
    featured: false,
    tagline: 'AI Image Forensics Platform',
    desc: '6+ model ensemble + Gemini 2.5 Flash to detect real which also used to Train model as like Teacher, AI generated, or deepfake images. Blockchain verdict registration on Ethereum Sepolia. Custom model that learns from user feedback.',
    tags: ['PyTorch', 'Gemini API', 'Streamlit', 'Solidity', 'Web3.py'],
    liveUrl: 'https://blocklens.streamlit.app',
    githubUrl: 'https://github.com/sejeeswarank/BlockLens',
  },
  {
    id: 'blocksafeguard', logoBg: '#111111',
    name: 'BlockSafeguard',
    logo: '/logos/blocksafeguard.png',
    featured: false,
    tagline: 'Enterprise DDoS Protection',
    desc: 'Dual-layer DDoS blocking (Flask + AWS NACL). All security actions logged immutably on blockchain. Firebase auth, role-based access, Docker + Gunicorn on AWS EC2.',
    tags: ['Flask', 'Solidity', 'AWS', 'Firebase', 'Docker', 'Web3.py'],
    liveUrl: 'https://blocksafeguard.vercel.app',
    githubUrl: 'https://github.com/sejeeswarank/BlockSafeguard',
  },
  {
    id: 'chronocare',
    name: 'ChronoCare AI',
    logo: '/logos/chronocare.png',
    featured: false,
    tagline: 'Chronic Disease Risk Engine',
    desc: 'Predicts Diabetes, Hypertension, CKD, CVD and more (literally for all diseases) using hybrid ML and clinical rules. Doctor, Patient portals with JWT auth and downloadable PDF clinical reports.',
    tags: ['Scikit-learn', 'Flask', 'React', 'TailwindCSS', 'ReportLab'],
    liveUrl: null,
    githubUrl: 'https://github.com/sejeeswarank/ChronoCare',
  },
  {
    id: 'sisteventcalendar',
    name: 'SIST Event Calendar',
    logo: '/logos/sisteventcalendar.png',
    featured: false,
    tagline: 'College Event Management',
    desc: 'Full stack event platform with role based access for Students, Organizers & Staff. TypeScript monorepo with Next.js 14 App Router and Firebase.',
    tags: ['TypeScript', 'Next.js 14', 'Firebase', 'Express', 'TailwindCSS'],
    liveUrl: 'https://sisteventcalendar.vercel.app',
    githubUrl: 'https://github.com/sejeeswarank/sisteventcalendar',
  },
]

export const skillCategories = [
  {
    id: 'languages',
    label: 'Languages',
    icon: 'code',
    skills: [
      { name: 'Python', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg' },
      { name: 'JavaScript', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg' },
      { name: 'TypeScript', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg' },
      { name: 'Solidity', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/solidity/solidity-original.svg' },
      { name: 'C', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg' },
      { name: 'SQL', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg' },
      { name: 'HTML5', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg' },
      { name: 'CSS3', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg' },
    ],
  },
  {
    id: 'frameworks',
    label: 'Frameworks',
    icon: 'layers',
    skills: [
      { name: 'React', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
      { name: 'Next.js 14', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg' },
      { name: 'Flask', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original.svg' },
      { name: 'Node.js', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg' },
      { name: 'Express', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg' },
      { name: 'Streamlit', logo: 'https://raw.githubusercontent.com/gilbarbara/logos/main/logos/streamlit.svg' },
      { name: 'TailwindCSS', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg' },
      { name: 'Bootstrap', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg' },
      { name: 'Pandas', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg' },
      { name: 'PyTorch', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg' },
    ],
  },
  {
    id: 'blockchain',
    label: 'Blockchain',
    icon: 'link',
    skills: [
      { name: 'Solidity', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/solidity/solidity-original.svg' },
      { name: 'Hardhat', logo: 'https://raw.githubusercontent.com/gilbarbara/logos/main/logos/hardhat-icon.svg' },
      { name: 'Web3.py', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/web3js/web3js-original.svg' },
      { name: 'Ethers.js', logo: 'https://raw.githubusercontent.com/gilbarbara/logos/main/logos/ethers.svg' },
      { name: 'MetaMask', logo: 'https://raw.githubusercontent.com/gilbarbara/logos/main/logos/metamask-icon.svg' },
      { name: 'Ethereum', logo: 'https://raw.githubusercontent.com/gilbarbara/logos/main/logos/ethereum.svg' },
      { name: 'Oracles', logo: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 60 69'%3E%3Cpath fill='%23375BD2' d='M30 0l8.7 5L30 10l-8.7-5L30 0zM0 15l8.7-5 8.7 5-8.7 5L0 15zm51.3 0l8.7-5-8.7 5zM8.7 20l8.7 5v10L8.7 40 0 35V25l8.7-5zm42.6 0L60 25v10l-8.7 5-8.7-5V25l8.7-5zM21.3 25L30 20l8.7 5v10L30 40l-8.7-5V25zM8.7 45l8.7 5-8.7 5L0 50l8.7-5zm42.6 0L60 50l-8.7 5-8.7-5 8.7-5zM21.3 50L30 45l8.7 5-8.7 5-8.7-5zM30 59l8.7 5L30 69l-8.7-5L30 59z'/%3E%3C/svg%3E" },
    ],
  },
  {
    id: 'databases',
    label: 'Databases',
    icon: 'database',
    skills: [
      { name: 'MongoDB', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg' },
      { name: 'MySQL', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg' },
      { name: 'SQLite', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sqlite/sqlite-original.svg' },
      { name: 'Firebase', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg' },
      { name: 'DBMS', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg' },
    ],
  },
  {
    id: 'cloud',
    label: 'Cloud & DevOps',
    icon: 'cloud',
    skills: [
      { name: 'AWS EC2/NACL', logo: 'https://raw.githubusercontent.com/gilbarbara/logos/main/logos/aws.svg' },
      { name: 'Docker', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg' },
      { name: 'Vercel', logo: 'https://raw.githubusercontent.com/gilbarbara/logos/main/logos/vercel-icon.svg' },
      { name: 'Git', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg' },
      { name: 'GitHub', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg' },
      { name: 'Linux', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg' },
      { name: 'Gunicorn', logo: 'https://raw.githubusercontent.com/gilbarbara/logos/main/logos/gunicorn.svg' },
    ],
  },
  {
    id: 'ai',
    label: 'AI / ML',
    icon: 'cpu',
    skills: [
      { name: 'Scikit-learn', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/scikitlearn/scikitlearn-original.svg' },
      { name: 'PyTorch', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg' },
      { name: 'Gemini API', logo: 'https://raw.githubusercontent.com/gilbarbara/logos/main/logos/google-gemini.svg' },
      { name: 'pdfplumber', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg' },
      { name: 'Fernet Encryption', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg' },
      { name: 'Pandas', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg' },
    ],
  },
]

export const certifications = [
  {
    issuer: 'Google · Coursera',
    name: 'Project Management Professional Certificate',
    url: 'https://coursera.org/share/3c399ef3e000abc17ffdcc9d31010193',
  },
  {
    issuer: 'HackerRank',
    name: 'Software Engineer Intern Certificate',
    url: 'https://www.hackerrank.com/certificates/3ac1a248182e',
  },
  {
    issuer: 'HackerRank',
    name: 'SQL (Advanced)',
    url: 'https://www.hackerrank.com/certificates/fbd3acc21b80',
  },
  {
    issuer: 'IBM · CognitiveClass',
    name: 'Combining Machine Learning and Rules for Cybersecurity',
    url: 'https://courses.cognitiveclass.ai/certificates/926a339c490d4441b8fed422978dd68c',
  },
  {
    issuer: 'IBM · CognitiveClass',
    name: 'Fundamentals of Encryption & Quantum-Safe Techniques',
    url: 'https://courses.cognitiveclass.ai/certificates/88066757edce43f194f2b1763e8e4182',
  },
  {
    issuer: 'Oracle',
    name: 'Cloud Infrastructure AI Foundations Associate',
    url: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=5FCA2B2F700CE3EB6D98CA627A393D9EFC2C534852B949FA4A7A087DC88F3B59',
  },
]